Neos:
  Flow:
    http:
      chain:
        postprocess:
          chain:
            setAllowCookie:
              position: 'after setSessionCookie'
              component: 'Netlogix\Varnish\AllowCookie\Component\SetAllowCookieComponent'
              componentOptions:
                allowedRequestPathPatterns:
                  - '#^/neos#'
