Neos:
  Flow:
    http:
      middlewares:
        'setAllowCookie':
          middleware: 'Netlogix\Varnish\AllowCookie\Middleware\SetAllowCookieMiddleware'
          position: 'after securityEntryPoint'
